//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservatoryCenter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SwitchSim.Switch")]
        public string SwitchDriverId {
            get {
                return ((string)(this["SwitchDriverId"]));
            }
            set {
                this["SwitchDriverId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\Diffraction Limited\\MaxIm DL V5\\MaxIm_DL.exe")]
        public string MaximDLPath {
            get {
                return ((string)(this["MaximDLPath"]));
            }
            set {
                this["MaximDLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\CCDWare\\CCDAutoPilot5\\CCDAutoPilot5.exe")]
        public string CCDAPPath {
            get {
                return ((string)(this["CCDAPPath"]));
            }
            set {
                this["CCDAPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\Ciel\\skychart.exe")]
        public string CartesPath {
            get {
                return ((string)(this["CartesPath"]));
            }
            set {
                this["CartesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string SwitchMountPort {
            get {
                return ((string)(this["SwitchMountPort"]));
            }
            set {
                this["SwitchMountPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string SwitchCameraPort {
            get {
                return ((string)(this["SwitchCameraPort"]));
            }
            set {
                this["SwitchCameraPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string SwitchRoofPowerPort {
            get {
                return ((string)(this["SwitchRoofPowerPort"]));
            }
            set {
                this["SwitchRoofPowerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string SwitchRoofSwitchPort {
            get {
                return ((string)(this["SwitchRoofSwitchPort"]));
            }
            set {
                this["SwitchRoofSwitchPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string SwitchFocuserPort {
            get {
                return ((string)(this["SwitchFocuserPort"]));
            }
            set {
                this["SwitchFocuserPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal RoofDuration {
            get {
                return ((decimal)(this["RoofDuration"]));
            }
            set {
                this["RoofDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RoofDurationMeasurementsCount {
            get {
                return ((decimal)(this["RoofDurationMeasurementsCount"]));
            }
            set {
                this["RoofDurationMeasurementsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EQMOD_SIM.Telescope")]
        public string TelescopeDriverId {
            get {
                return ((string)(this["TelescopeDriverId"]));
            }
            set {
                this["TelescopeDriverId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASCOM.Simulator.Dome")]
        public string DomeDriverId {
            get {
                return ((string)(this["DomeDriverId"]));
            }
            set {
                this["DomeDriverId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceEnabled_Switch {
            get {
                return ((bool)(this["DeviceEnabled_Switch"]));
            }
            set {
                this["DeviceEnabled_Switch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceEnabled_Dome {
            get {
                return ((bool)(this["DeviceEnabled_Dome"]));
            }
            set {
                this["DeviceEnabled_Dome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceEnabled_Telescope {
            get {
                return ((bool)(this["DeviceEnabled_Telescope"]));
            }
            set {
                this["DeviceEnabled_Telescope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public string LongGrad {
            get {
                return ((string)(this["LongGrad"]));
            }
            set {
                this["LongGrad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LongMin {
            get {
                return ((string)(this["LongMin"]));
            }
            set {
                this["LongMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LongSec {
            get {
                return ((string)(this["LongSec"]));
            }
            set {
                this["LongSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public string LatGrad {
            get {
                return ((string)(this["LatGrad"]));
            }
            set {
                this["LatGrad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LatMin {
            get {
                return ((string)(this["LatMin"]));
            }
            set {
                this["LatMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LatSec {
            get {
                return ((string)(this["LatSec"]));
            }
            set {
                this["LatSec"] = value;
            }
        }
    }
}
