//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservatoryCenter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SwitchDriverId {
            get {
                return ((string)(this["SwitchDriverId"]));
            }
            set {
                this["SwitchDriverId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\Diffraction Limited\\MaxIm DL V5\\MaxIm_DL.exe")]
        public string MaximDLPath {
            get {
                return ((string)(this["MaximDLPath"]));
            }
            set {
                this["MaximDLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\CCDWare\\CCDAutoPilot5\\CCDAutoPilot5.exe")]
        public string CCDAPPath {
            get {
                return ((string)(this["CCDAPPath"]));
            }
            set {
                this["CCDAPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\Ciel\\skychart.exe")]
        public string CartesPath {
            get {
                return ((string)(this["CartesPath"]));
            }
            set {
                this["CartesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string SwitchMountPort {
            get {
                return ((string)(this["SwitchMountPort"]));
            }
            set {
                this["SwitchMountPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string SwitchCameraPort {
            get {
                return ((string)(this["SwitchCameraPort"]));
            }
            set {
                this["SwitchCameraPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string SwitchRoofPowerPort {
            get {
                return ((string)(this["SwitchRoofPowerPort"]));
            }
            set {
                this["SwitchRoofPowerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string SwitchRoofSwitchPort {
            get {
                return ((string)(this["SwitchRoofSwitchPort"]));
            }
            set {
                this["SwitchRoofSwitchPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string SwitchFocuserPort {
            get {
                return ((string)(this["SwitchFocuserPort"]));
            }
            set {
                this["SwitchFocuserPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal RoofDuration {
            get {
                return ((decimal)(this["RoofDuration"]));
            }
            set {
                this["RoofDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RoofDurationMeasurementsCount {
            get {
                return ((decimal)(this["RoofDurationMeasurementsCount"]));
            }
            set {
                this["RoofDurationMeasurementsCount"] = value;
            }
        }
    }
}
